# Generated by Django 5.2 on 2026-07-17 10:30

import apps.common.utils.file_path_renamer
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number is not correct. Example: '+998901234567'", regex='^\\+998([0-9]{2})[0-9]{7}$')], verbose_name='phone')),
                ('hotline', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number is not correct. Example: '+998901234567'", regex='^\\+998([0-9]{2})[0-9]{7}$')], verbose_name='hotline')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='address')),
                ('work_hours', models.JSONField(blank=True, default=dict, verbose_name='work hours')),
                ('yandex_map_url', models.URLField(blank=True, verbose_name='Yandex map URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('catalog_file', models.FileField(blank=True, upload_to=apps.common.utils.file_path_renamer.PathAndRename('pages/settings'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='catalog file')),
                ('cookie_notice_text', models.JSONField(blank=True, default=dict, verbose_name='cookie notice text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='slug')),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='body')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'static page',
                'verbose_name_plural': 'static pages',
                'ordering': ('slug',),
            },
        ),
    ]
