# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_privacypolicy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypolicy",
            options={
                "ordering": ("slug",),
                "verbose_name": "privacy policy",
                "verbose_name_plural": "privacy policy",
            },
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="slug",
            field=models.SlugField(db_index=True, default="", max_length=170, unique=True, verbose_name="slug"),
            preserve_default=False,
        ),
    ]
