# Generated by Django 5.2 on 2026-09-01 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_privacypolicy_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('partner', 'partner')], db_index=True, help_text='partner - partner', max_length=16, verbose_name='banner type')),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('subtitle', models.JSONField(blank=True, default=dict, verbose_name='subtitle')),
                ('image', models.CharField(max_length=500, verbose_name='image')),
                ('cta_label', models.JSONField(blank=True, default=dict, verbose_name='CTA label')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['type', 'id'], name='pages_banne_type_29c89d_idx')],
            },
        ),
    ]
