# Generated by Django 5.2.5 on 2026-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="cta_label",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="CTA label"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="cta_url",
            field=models.URLField(blank=True, null=True, verbose_name="CTA URL"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="subtitle",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[("partner", "partner"), ("main", "main")],
                db_index=True,
                help_text="partner - partner, main - main",
                max_length=16,
                verbose_name="banner type",
            ),
        ),
    ]
