# Generated by Django 5.2.5 on 2026-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_banner_cta_label_alter_banner_cta_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[
                    ("main", "main"),
                    ("about", "about"),
                    ("carrier", "carrier"),
                    ("partner", "partner"),
                ],
                db_index=True,
                help_text="main - main, about - about, carrier - carrier, partner - partner",
                max_length=16,
                verbose_name="banner type",
            ),
        ),
    ]
