# Generated by Django 5.2 on 2026-07-17 10:14

import apps.common.utils.file_path_renamer
import apps.common.utils.image_validate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='first name')),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='X position')),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Y position')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'export region',
                'verbose_name_plural': 'export regions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('subtitle', models.JSONField(blank=True, default=dict, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('about/slides'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('cta_label', models.JSONField(blank=True, default=dict, verbose_name='CTA label')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'home slide',
                'verbose_name_plural': 'home slides',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=16, verbose_name='value')),
                ('label', models.JSONField(default=dict, verbose_name='label')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stat',
                'verbose_name_plural': 'stats',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='year')),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to=apps.common.utils.file_path_renamer.PathAndRename('about/timeline'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timeline event',
                'verbose_name_plural': 'timeline events',
                'ordering': ('year',),
            },
        ),
    ]
