# Generated by Django 5.2.5 on 2026-08-30 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_homeslide_image_alter_timelineevent_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.JSONField(default=dict, verbose_name="title")),
                (
                    "subtitle",
                    models.JSONField(blank=True, default=dict, verbose_name="subtitle"),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="description"
                    ),
                ),
                (
                    "subdescription",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="subdescription"
                    ),
                ),
                ("image", models.CharField(max_length=500, verbose_name="image")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "factory",
                "verbose_name_plural": "factory",
            },
        ),
    ]
