# Generated by Django 5.2.5 on 2026-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_productinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslide",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="stat",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="active"),
        ),
    ]
