# Generated by Django 5.2 on 2026-07-17 10:30

import apps.common.utils.file_path_renamer
import apps.common.utils.image_validate
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('image', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('partners/certificates'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('file', models.FileField(blank=True, upload_to=apps.common.utils.file_path_renamer.PathAndRename('partners/certificates/files'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='first name')),
                ('logo', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('partners/logos'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ('name',),
            },
        ),
    ]
