# Generated by Django 5.2 on 2026-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.CharField(blank=True, max_length=500, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.CharField(max_length=500, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(max_length=500, verbose_name='logo'),
        ),
    ]
