# Generated by Django 5.2 on 2026-07-17 10:14

import apps.common.utils.file_path_renamer
import apps.common.utils.image_validate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('excerpt', models.JSONField(blank=True, default=dict, verbose_name='excerpt')),
                ('cover', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('blog/posts'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='cover')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='published at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('heading', 'heading'), ('text', 'text'), ('image', 'image')], max_length=16, verbose_name='block type')),
                ('text', models.JSONField(blank=True, default=dict, verbose_name='text')),
                ('image', models.ImageField(blank=True, upload_to=apps.common.utils.file_path_renamer.PathAndRename('blog/blocks'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.post', verbose_name='post')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post block',
                'verbose_name_plural': 'post blocks',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_at'], name='blog_post_is_publ_9ad937_idx'),
        ),
    ]
