# Generated by Django 5.2 on 2026-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.CharField(max_length=500, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='postblock',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='image'),
        ),
    ]
