# Generated by Django 5.2 on 2026-07-17 09:55

import apps.common.utils.file_path_renamer
import apps.common.utils.image_validate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='first name')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('catalog/categories'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='first name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'flavor',
                'verbose_name_plural': 'flavors',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='first name')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product family',
                'verbose_name_plural': 'product families',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default=dict, verbose_name='first name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.JSONField(blank=True, default=dict, verbose_name='description')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('box_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='box weight')),
                ('shelf_life_months', models.PositiveSmallIntegerField(verbose_name='shelf life (months)')),
                ('badge', models.CharField(blank=True, choices=[('', ''), ('new', 'new'), ('bestseller', 'bestseller')], default='', max_length=16, verbose_name='badge')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.flavor', verbose_name='flavor')),
                ('related_products', models.ManyToManyField(blank=True, related_name='recommended_by', to='catalog.product', verbose_name='related products')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productfamily', verbose_name='product family')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.common.utils.file_path_renamer.PathAndRename('catalog/products'), validators=[apps.common.utils.image_validate.validate_file_size, apps.common.utils.image_validate.validate_image_size], verbose_name='image')),
                ('alt', models.JSONField(blank=True, default=dict, verbose_name='alt text')),
                ('is_main', models.BooleanField(default=False, verbose_name='is main')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='value')),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram')], max_length=2, verbose_name='unit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'weight',
                'verbose_name_plural': 'weights',
                'ordering': ('unit', 'value'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='weights',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.weight', verbose_name='weights'),
        ),
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(fields=('value', 'unit'), name='unique_weight_value_unit'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='catalog_pro_categor_0e06cf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['badge'], name='catalog_pro_badge_b29463_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='catalog_pro_is_feat_94b8d5_idx'),
        ),
    ]
