# Generated by Django 5.2.5 on 2026-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_badge_alter_weight_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("new", "new"),
                    ("bestseller", "bestseller"),
                    ("discount", "discount"),
                ],
                default="",
                help_text=" - , new - new, bestseller - bestseller, discount - discount",
                max_length=16,
                verbose_name="badge",
            ),
        ),
    ]
