# Generated by Django 5.2 on 2026-07-17 10:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='unsubscribe token')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('partner', 'partner'), ('sales', 'sales'), ('contact', 'contact')], db_index=True, max_length=16, verbose_name='lead type')),
                ('name', models.CharField(max_length=150, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number is not correct. Example: '+998901234567'", regex='^\\+998([0-9]{2})[0-9]{7}$')], verbose_name='phone number')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('consent_personal_data', models.BooleanField(default=False, verbose_name='consent to personal data processing')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='consent to marketing')),
                ('status', models.CharField(choices=[('new', 'new'), ('in_progress', 'In progress'), ('done', 'done')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('source_url', models.URLField(blank=True, verbose_name='source URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product', verbose_name='product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'status', '-created_at'], name='leads_lead_type_de5c61_idx')],
            },
        ),
    ]
