# Generated by Django 5.2 on 2026-07-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-id',), 'verbose_name': 'lead', 'verbose_name_plural': 'leads'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ('-id',), 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
    ]
